-- --------------------------------------------------------
-- Host:                         172.70.7.23
-- Versión del servidor:         8.0.21 - MySQL Community Server - GPL
-- SO del servidor:              Win64
-- HeidiSQL Versión:             9.4.0.5125
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- Volcando estructura de base de datos para dbp_what_samaritana
CREATE DATABASE IF NOT EXISTS `dbp_what_samaritana` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
USE `dbp_what_samaritana`;

-- Volcando estructura para tabla dbp_what_samaritana.sessions
CREATE TABLE IF NOT EXISTS `sessions` (
  `session_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `expires` int unsigned NOT NULL,
  `data` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  PRIMARY KEY (`session_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- La exportación de datos fue deseleccionada.
-- Volcando estructura para tabla dbp_what_samaritana.tbl_gestion
CREATE TABLE IF NOT EXISTS `tbl_gestion` (
  `PKGES_CODIGO` int NOT NULL AUTO_INCREMENT,
  `FKGES_NENV_CODIGO` int DEFAULT NULL,
  `FKGES_NPER_CODIGO` varchar(45) DEFAULT NULL,
  `GES_ESTADO_CASO` varchar(45) DEFAULT NULL,
  `GES_NENV_CODIGO` bigint DEFAULT NULL,
  `GES_NUMERO_COMUNICA` bigint DEFAULT NULL,
  `GES_CULT_MSGBOT` text,
  `GES_CDETALLE` text,
  `GES_CDETALLE1` text,
  `GES_CDETALLE2` text,
  `GES_CDETALLE3` text,
  `GES_CDETALLE4` text,
  `GES_CDETALLE5` text,
  `GES_CDETALLE6` text,
  `GES_CDETALLE7` text,
  `GES_CDETALLE8` text,
  `GES_CDETALLE9` text,
  `GES_CDETALLE10` text,
  `GES_CDETALLE11` text,
  `GES_CDETALLE12` text,
  `GES_CDETALLE13` text,
  `GES_CDETALLE14` text,
  `GES_CDETALLE15` text,
  `GES_CDETALLE16` text,
  `GES_CDETALLE17` text,
  `GES_CDETALLE18` text,
  `GES_CSINTOMAS` text,
  `GES_CFECHA_REGISTRO` text,
  `GES_CFECHA_MODIFICACION` text,
  `GES_CDETALLE_REGISTRO` text,
  `GES_CTIPIFICACION1` varchar(45) DEFAULT NULL,
  `GES_CTIPIFICACION2` varchar(45) DEFAULT NULL,
  `GES_CDETADICIONAL` varchar(1500) DEFAULT NULL,
  `GES_CESTADO` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`PKGES_CODIGO`)
) ENGINE=InnoDB AUTO_INCREMENT=122 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- La exportación de datos fue deseleccionada.
-- Volcando estructura para tabla dbp_what_samaritana.tbl_mensajes_chat
CREATE TABLE IF NOT EXISTS `tbl_mensajes_chat` (
  `PKMEN_NCODIGO` int NOT NULL AUTO_INCREMENT,
  `FK_GES_CODIGO` int NOT NULL,
  `MEN_ESTADO_MENSAJE` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `MEN_NUMERO_ORIGEN` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `MEN_NUMERO_DESTINO` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `MEN_TIPO_MENSAJE` varchar(45) DEFAULT NULL,
  `MEN_TEXTO` varchar(3000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `MEN_RUTA_MEDIA` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `MEN_CFECHA_REGISTRO` datetime DEFAULT NULL,
  `MEN_CFECHA_MODIFICACION` datetime DEFAULT NULL,
  `MEN_CDETALLE_REGISTRO` varchar(255) DEFAULT NULL,
  `MEN_CESTADO` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`PKMEN_NCODIGO`)
) ENGINE=InnoDB AUTO_INCREMENT=598 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- La exportación de datos fue deseleccionada.
-- Volcando estructura para tabla dbp_what_samaritana.tbl_rcredencial
CREATE TABLE IF NOT EXISTS `tbl_rcredencial` (
  `PKCRE_NCODIGO` int NOT NULL AUTO_INCREMENT,
  `CRE_CUSUARIO` varchar(255) DEFAULT NULL,
  `CRE_CNOMBRE` varchar(255) DEFAULT NULL,
  `CRE_CNOMBRE2` varchar(255) DEFAULT NULL,
  `CRE_CAPELLIDO` varchar(255) DEFAULT NULL,
  `CRE_CAPELLIDO2` varchar(255) DEFAULT NULL,
  `CRE_CIDAGENTE` varchar(255) DEFAULT NULL,
  `CRE_CDOCUMENTO` varchar(255) DEFAULT NULL,
  `CRE_CFECHA_REGISTRO` datetime DEFAULT NULL,
  `CRE_CFECHA_MODIFICACION` datetime DEFAULT NULL,
  `CRE_CDETALLE_REGISTRO` varchar(255) DEFAULT NULL,
  `CRE_CESTADO` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`PKCRE_NCODIGO`)
) ENGINE=InnoDB AUTO_INCREMENT=34456 DEFAULT CHARSET=utf8;

-- La exportación de datos fue deseleccionada.
-- Volcando estructura para tabla dbp_what_samaritana.tbl_rpermiso
CREATE TABLE IF NOT EXISTS `tbl_rpermiso` (
  `PKPER_NCODIGO` int NOT NULL AUTO_INCREMENT,
  `FKPER_NCRE_NCODIGO` int DEFAULT NULL,
  `PER_CNIVEL` text,
  `PER_CCONTRASENA` text,
  `PER_CPERMISO` text,
  `PER_CCLIENTE` text,
  `PER_CMACRO` text,
  `PER_CCAMPANA` text,
  `PER_CAREA` text,
  `PER_CGRUPO` text,
  `PER_CSUBGRUPO` text,
  `PER_CCARGO` text,
  `PER_CFECHA_LOGUEO` text,
  `PER_CTIPOLOGUEO` text,
  `PER_CESTADO_LOGUEO` text,
  `PER_CFECHA_REGISTRO` text,
  `PER_CFECHA_MODIFICACION` text,
  `PER_CDETALLE_REGISTRO` text,
  `PER_CESTADO` text,
  `PER_AUXILIAR` varchar(45) DEFAULT NULL,
  `PER_TIEMPOAUXILIAR` datetime DEFAULT NULL,
  PRIMARY KEY (`PKPER_NCODIGO`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- La exportación de datos fue deseleccionada.
-- Volcando estructura para disparador dbp_what_samaritana.TRIGGUER_INSERT_G2
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `TRIGGUER_INSERT_G2` BEFORE INSERT ON `tbl_gestion` FOR EACH ROW SET NEW.GES_CFECHA_REGISTRO = now()//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador dbp_what_samaritana.TRIGGUER_INSERT_RP1
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `TRIGGUER_INSERT_RP1` BEFORE INSERT ON `tbl_rpermiso` FOR EACH ROW SET NEW.PER_CFECHA_REGISTRO = now()//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador dbp_what_samaritana.TRIGGUER_INSERT_RP2
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `TRIGGUER_INSERT_RP2` BEFORE INSERT ON `tbl_rcredencial` FOR EACH ROW SET NEW.CRE_CFECHA_REGISTRO = now()//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador dbp_what_samaritana.TRIGGUER_INSERT_W2
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `TRIGGUER_INSERT_W2` BEFORE INSERT ON `tbl_mensajes_chat` FOR EACH ROW SET NEW.MEN_CFECHA_REGISTRO = now()//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador dbp_what_samaritana.TRIGGUER_UPDATE_G1
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `TRIGGUER_UPDATE_G1` BEFORE UPDATE ON `tbl_gestion` FOR EACH ROW SET NEW.GES_CFECHA_MODIFICACION = now()//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador dbp_what_samaritana.TRIGGUER_UPDATE_RP1
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `TRIGGUER_UPDATE_RP1` BEFORE UPDATE ON `tbl_rpermiso` FOR EACH ROW SET NEW.PER_CFECHA_MODIFICACION = now()//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador dbp_what_samaritana.TRIGGUER_UPDATE_RP2
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `TRIGGUER_UPDATE_RP2` BEFORE UPDATE ON `tbl_rcredencial` FOR EACH ROW SET NEW.CRE_CFECHA_MODIFICACION = now()//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador dbp_what_samaritana.TRIGGUER_UPDATE_W2
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `TRIGGUER_UPDATE_W2` BEFORE UPDATE ON `tbl_mensajes_chat` FOR EACH ROW SET NEW.MEN_CFECHA_MODIFICACION = now()//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para tabla dbp_what_samaritana.sessions
CREATE TABLE IF NOT EXISTS `sessions` (
  `session_id` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `expires` int unsigned NOT NULL,
  `data` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  PRIMARY KEY (`session_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- La exportación de datos fue deseleccionada.
-- Volcando estructura para tabla dbp_what_samaritana.tbl_gestion
CREATE TABLE IF NOT EXISTS `tbl_gestion` (
  `PKGES_CODIGO` int NOT NULL AUTO_INCREMENT,
  `FKGES_NENV_CODIGO` int DEFAULT NULL,
  `FKGES_NPER_CODIGO` varchar(45) DEFAULT NULL,
  `GES_ESTADO_CASO` varchar(45) DEFAULT NULL,
  `GES_NENV_CODIGO` bigint DEFAULT NULL,
  `GES_NUMERO_COMUNICA` bigint DEFAULT NULL,
  `GES_CULT_MSGBOT` text,
  `GES_CDETALLE` text,
  `GES_CDETALLE1` text,
  `GES_CDETALLE2` text,
  `GES_CDETALLE3` text,
  `GES_CDETALLE4` text,
  `GES_CDETALLE5` text,
  `GES_CDETALLE6` text,
  `GES_CDETALLE7` text,
  `GES_CDETALLE8` text,
  `GES_CDETALLE9` text,
  `GES_CDETALLE10` text,
  `GES_CDETALLE11` text,
  `GES_CDETALLE12` text,
  `GES_CDETALLE13` text,
  `GES_CDETALLE14` text,
  `GES_CDETALLE15` text,
  `GES_CDETALLE16` text,
  `GES_CDETALLE17` text,
  `GES_CDETALLE18` text,
  `GES_CSINTOMAS` text,
  `GES_CFECHA_REGISTRO` text,
  `GES_CFECHA_MODIFICACION` text,
  `GES_CDETALLE_REGISTRO` text,
  `GES_CTIPIFICACION1` varchar(45) DEFAULT NULL,
  `GES_CTIPIFICACION2` varchar(45) DEFAULT NULL,
  `GES_CDETADICIONAL` varchar(1500) DEFAULT NULL,
  `GES_CESTADO` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`PKGES_CODIGO`)
) ENGINE=InnoDB AUTO_INCREMENT=122 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- La exportación de datos fue deseleccionada.
-- Volcando estructura para tabla dbp_what_samaritana.tbl_mensajes_chat
CREATE TABLE IF NOT EXISTS `tbl_mensajes_chat` (
  `PKMEN_NCODIGO` int NOT NULL AUTO_INCREMENT,
  `FK_GES_CODIGO` int NOT NULL,
  `MEN_ESTADO_MENSAJE` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `MEN_NUMERO_ORIGEN` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `MEN_NUMERO_DESTINO` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `MEN_TIPO_MENSAJE` varchar(45) DEFAULT NULL,
  `MEN_TEXTO` varchar(3000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `MEN_RUTA_MEDIA` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `MEN_CFECHA_REGISTRO` datetime DEFAULT NULL,
  `MEN_CFECHA_MODIFICACION` datetime DEFAULT NULL,
  `MEN_CDETALLE_REGISTRO` varchar(255) DEFAULT NULL,
  `MEN_CESTADO` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`PKMEN_NCODIGO`)
) ENGINE=InnoDB AUTO_INCREMENT=598 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- La exportación de datos fue deseleccionada.
-- Volcando estructura para tabla dbp_what_samaritana.tbl_rcredencial
CREATE TABLE IF NOT EXISTS `tbl_rcredencial` (
  `PKCRE_NCODIGO` int NOT NULL AUTO_INCREMENT,
  `CRE_CUSUARIO` varchar(255) DEFAULT NULL,
  `CRE_CNOMBRE` varchar(255) DEFAULT NULL,
  `CRE_CNOMBRE2` varchar(255) DEFAULT NULL,
  `CRE_CAPELLIDO` varchar(255) DEFAULT NULL,
  `CRE_CAPELLIDO2` varchar(255) DEFAULT NULL,
  `CRE_CIDAGENTE` varchar(255) DEFAULT NULL,
  `CRE_CDOCUMENTO` varchar(255) DEFAULT NULL,
  `CRE_CFECHA_REGISTRO` datetime DEFAULT NULL,
  `CRE_CFECHA_MODIFICACION` datetime DEFAULT NULL,
  `CRE_CDETALLE_REGISTRO` varchar(255) DEFAULT NULL,
  `CRE_CESTADO` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`PKCRE_NCODIGO`)
) ENGINE=InnoDB AUTO_INCREMENT=34456 DEFAULT CHARSET=utf8;

-- La exportación de datos fue deseleccionada.
-- Volcando estructura para tabla dbp_what_samaritana.tbl_rpermiso
CREATE TABLE IF NOT EXISTS `tbl_rpermiso` (
  `PKPER_NCODIGO` int NOT NULL AUTO_INCREMENT,
  `FKPER_NCRE_NCODIGO` int DEFAULT NULL,
  `PER_CNIVEL` text,
  `PER_CCONTRASENA` text,
  `PER_CPERMISO` text,
  `PER_CCLIENTE` text,
  `PER_CMACRO` text,
  `PER_CCAMPANA` text,
  `PER_CAREA` text,
  `PER_CGRUPO` text,
  `PER_CSUBGRUPO` text,
  `PER_CCARGO` text,
  `PER_CFECHA_LOGUEO` text,
  `PER_CTIPOLOGUEO` text,
  `PER_CESTADO_LOGUEO` text,
  `PER_CFECHA_REGISTRO` text,
  `PER_CFECHA_MODIFICACION` text,
  `PER_CDETALLE_REGISTRO` text,
  `PER_CESTADO` text,
  `PER_AUXILIAR` varchar(45) DEFAULT NULL,
  `PER_TIEMPOAUXILIAR` datetime DEFAULT NULL,
  PRIMARY KEY (`PKPER_NCODIGO`)
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- La exportación de datos fue deseleccionada.
-- Volcando estructura para disparador dbp_what_samaritana.TRIGGUER_INSERT_G2
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `TRIGGUER_INSERT_G2` BEFORE INSERT ON `tbl_gestion` FOR EACH ROW SET NEW.GES_CFECHA_REGISTRO = now()//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador dbp_what_samaritana.TRIGGUER_INSERT_RP1
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `TRIGGUER_INSERT_RP1` BEFORE INSERT ON `tbl_rpermiso` FOR EACH ROW SET NEW.PER_CFECHA_REGISTRO = now()//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador dbp_what_samaritana.TRIGGUER_INSERT_RP2
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `TRIGGUER_INSERT_RP2` BEFORE INSERT ON `tbl_rcredencial` FOR EACH ROW SET NEW.CRE_CFECHA_REGISTRO = now()//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador dbp_what_samaritana.TRIGGUER_INSERT_W2
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `TRIGGUER_INSERT_W2` BEFORE INSERT ON `tbl_mensajes_chat` FOR EACH ROW SET NEW.MEN_CFECHA_REGISTRO = now()//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador dbp_what_samaritana.TRIGGUER_UPDATE_G1
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `TRIGGUER_UPDATE_G1` BEFORE UPDATE ON `tbl_gestion` FOR EACH ROW SET NEW.GES_CFECHA_MODIFICACION = now()//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador dbp_what_samaritana.TRIGGUER_UPDATE_RP1
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `TRIGGUER_UPDATE_RP1` BEFORE UPDATE ON `tbl_rpermiso` FOR EACH ROW SET NEW.PER_CFECHA_MODIFICACION = now()//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador dbp_what_samaritana.TRIGGUER_UPDATE_RP2
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `TRIGGUER_UPDATE_RP2` BEFORE UPDATE ON `tbl_rcredencial` FOR EACH ROW SET NEW.CRE_CFECHA_MODIFICACION = now()//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

-- Volcando estructura para disparador dbp_what_samaritana.TRIGGUER_UPDATE_W2
SET @OLDTMP_SQL_MODE=@@SQL_MODE, SQL_MODE='STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION';
DELIMITER //
CREATE TRIGGER `TRIGGUER_UPDATE_W2` BEFORE UPDATE ON `tbl_mensajes_chat` FOR EACH ROW SET NEW.MEN_CFECHA_MODIFICACION = now()//
DELIMITER ;
SET SQL_MODE=@OLDTMP_SQL_MODE;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
